<wsdl:definitions
     name="DBstudentsGender"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/DBstudentsGender"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/DBstudentsGender"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/DBstudentsGender"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="DBstudentsGender_plt" >
    <plt:role name="DBstudentsGender_role" >
      <plt:portType name="tns:DBstudentsGender_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/DBstudentsGender" schemaLocation="DBstudentsGender.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="DBstudentsGenderInput_msg">
        <wsdl:part name="DBstudentsGenderInput_msg" element="db:DBstudentsGenderInput"/>
    </wsdl:message>
    <wsdl:message name="DBstudentsGenderOutputCollection_msg">
        <wsdl:part name="DBstudentsGenderOutputCollection" element="db:DBstudentsGenderOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="DBstudentsGender_ptt">
        <wsdl:operation name="DBstudentsGender">
            <wsdl:input message="tns:DBstudentsGenderInput_msg"/>
            <wsdl:output message="tns:DBstudentsGenderOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
