<wsdl:definitions
     name="getNumeroAlumnosTit"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/getNumeroAlumnosTit"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/getNumeroAlumnosTit"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/getNumeroAlumnosTit"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="getNumeroAlumnosTit_plt" >
    <plt:role name="getNumeroAlumnosTit_role" >
      <plt:portType name="tns:getNumeroAlumnosTit_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/getNumeroAlumnosTit" schemaLocation="getNumeroAlumnosTit.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="getNumeroAlumnosTitInput_msg">
        <wsdl:part name="getNumeroAlumnosTitInput_msg" element="db:getNumeroAlumnosTitInput"/>
    </wsdl:message>
    <wsdl:message name="getNumeroAlumnosTitOutputCollection_msg">
        <wsdl:part name="getNumeroAlumnosTitOutputCollection" element="db:getNumeroAlumnosTitOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="getNumeroAlumnosTit_ptt">
        <wsdl:operation name="getNumeroAlumnosTit">
            <wsdl:input message="tns:getNumeroAlumnosTitInput_msg"/>
            <wsdl:output message="tns:getNumeroAlumnosTitOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
