<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/getStudentsData" name="getStudentsData-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="getStudentsData.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/getStudentsData"/>
    <wsdl:binding name="getStudentsData_ptt-binding" type="get:getStudentsData_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/TFM-SB/ull-alumno/getStudentsData">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="getStudentsDataSelect">
            <soap:operation soapAction="getStudentsDataSelect"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>